github: [noplanman]
tidelift: packagist/longman/telegram-bot
patreon: phptelegrambot
liberapay: PHP-Telegram-Bot
open_collective: php-telegram-bot
ko_fi: phptelegrambot
custom: https://github.com/php-telegram-bot/core#donate
