version: '3'
services:
  php:
    build: docker/php
    volumes:
      - ./:/app

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  database:
    image: mariadb
    volumes:
      - ./packages/php-telegram-bot/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

  api-server:
    image: tdlight/tdlightbotapi
    environment:
      TELEGRAM_API_ID: $TELEGRAM_API_ID
      TELEGRAM_API_HASH: $TELEGRAM_API_HASH
      TELEGRAM_LOCAL: yes